### ISSUE TITLE
0.0.2 checklist

### ISSUE THREAD

**Issue by topepo** [tidymodels/embed#12]
Prepare for release:

* [ ] `devtools::check_win_devel()`
* [ ] `rhub::check_for_cran()`
* [ ] `revdepcheck::revdep_check(num_workers = 4)`
* [ ] [Polish NEWS](http://style.tidyverse.org/news.html#before-release)
* [ ] If new failures, update `email.yml` then `revdepcheck::revdep_email_maintainers()`

Perform release:

* [ ] Create RC branch (for bigger releases)
* [ ] Bump version (in DESCRIPTION and NEWS)
* [ ] `devtools::check_win_devel()` (again!)
* [ ] `devtools::submit_cran()`
* [ ] Approve email

Wait for CRAN...

* [ ] Tag release
* [ ] Merge RC back to master branch
* [ ] `pkgdown::build_site()`
* [ ] Bump dev version
*  ~Write blog post~ Deferred for a `tidymodels` general update. 

Template from <https://github.com/r-lib/usethis/issues/338>
